
paginate: 1 
permalink: :title/
paginate_path: "page:num"
gems:
    - jekyll-paginate
exclude:
    - "README.md" 
highlighter: pygments
markdown: kramdown
kramdown:
    input: GFM

defaults:
  -
    scope:
      path: "" 
    values:
      title: PHP PhantomJS

collections:
  version_3:
    output: true
    permalink: /3.0/:title/
  version_4:
    output: true
    permalink: /4.0/:title/

title: PHP PhantomJs
description: Run PhantomJS scripts through PHP

author:
  name: Jonny W

github:
  username: jonnnnyw
  repo: php-phantomjs
  watch: true
  fork: true

rss_path: feed.xml

latest_version: 4.0
latest_collection: version_4

BASE_PATH: http://jonnnnyw.github.io/php-phantomjs
